---
apiVersion: v1
kind: Secret
metadata:
  name: {{.Values.git.credentials.secret}}
  labels:
    {{- include "artigit.labels" . | nindent 4 }}
data:
  username: {{.Values.git.credentials.username | b64enc | quote}}
  password: {{.Values.git.credentials.password | b64enc | quote}}
